### ISSUE TITLE
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory

### ISSUE THREAD

**Issue by dbjpanda** [drupal-docker/php#92] opened 2018-05-10 22:19 UTC
+ apk add --virtual .drupal-phpexts-rundeps so:libc.musl-x86_64.so.1 so:libcrypto.so.41 so:libcurl.so.4 so:libedit.so.0 so:libfreetype.so.6 so:libjpeg.so.8 so:libpng16.so.16 so:libpq.so.5 so:libsodium.so.18 so:libssl.so.43 so:libxml2.so.2 so:libz.so.1
WARNING: Ignoring APKINDEX.84815163.tar.gz: No such file or directory
WARNING: Ignoring APKINDEX.24d64ab1.tar.gz: No such file or directory

**Comment by zaporylie** [comment] 2018-07-04 09:28
I cannot reproduce this issue, hence closing. Feel free to comment with steps how to reproduce it.

**Closed as completed by zaporylie** 2018-07-04 09:28 UTC

**Comment by dbjpanda** [comment] 2018-07-04 12:05
@zaporylie Sometimes while building the image,  It shows this warning and sometimes doesn't show.

**Comment by zaporylie** [comment] 2018-07-04 13:42
@dbjpanda Thanks for feedback. I believe the issue is related to apk rather than this project.

**Comment by andypost** [comment] 2018-07-04 15:45
Looks it was fixed because all places now use `apk add -no-cache`
